{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.7.1.jar",
          "url": "reactor-core-3.7.1.jar",
          "size": 1878532,
          "sha512": "17a7ab6bb0ce3ecb2147dea1165a68ed9c17299cca5c4cf7f2acf5b256f8f487d9661bf922983492a9ff386ca2c97b276d5fde74884484ff9f576dc0cbc9fc7b",
          "sha256": "9351d3bbbfad56176669d88ff8f62c4a9127b06636334cd5ec263276ed40f964",
          "sha1": "3391286019effb6c179ebbdd2159130dde543c3a",
          "md5": "df2041ce3788ab5f27ad3642dc212469"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.7.1.jar",
          "url": "reactor-core-3.7.1.jar",
          "size": 1878532,
          "sha512": "17a7ab6bb0ce3ecb2147dea1165a68ed9c17299cca5c4cf7f2acf5b256f8f487d9661bf922983492a9ff386ca2c97b276d5fde74884484ff9f576dc0cbc9fc7b",
          "sha256": "9351d3bbbfad56176669d88ff8f62c4a9127b06636334cd5ec263276ed40f964",
          "sha1": "3391286019effb6c179ebbdd2159130dde543c3a",
          "md5": "df2041ce3788ab5f27ad3642dc212469"
        }
      ]
    }
  ]
}
