{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webflux",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.2.1.jar",
          "url": "spring-webflux-6.2.1.jar",
          "size": 1013978,
          "sha512": "8411dead81bf1d7e2eea4cbd492e71f710d2c57d73ce5dfa4e79ea411067b6b755c61dea385414ec2491d92a1fb3c07f97b77fde6cf6331e1e149be6739f8a16",
          "sha256": "d29a4a95666bfa8258b3a102b8eaeb60f05ede65b79991e50a0ebd80b9b10c24",
          "sha1": "f8563a18b02c0aa1f7cd1ee298e76abd3514822b",
          "md5": "79afaa9f079a0f14db4929387dbf0592"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.2.1.jar",
          "url": "spring-webflux-6.2.1.jar",
          "size": 1013978,
          "sha512": "8411dead81bf1d7e2eea4cbd492e71f710d2c57d73ce5dfa4e79ea411067b6b755c61dea385414ec2491d92a1fb3c07f97b77fde6cf6331e1e149be6739f8a16",
          "sha256": "d29a4a95666bfa8258b3a102b8eaeb60f05ede65b79991e50a0ebd80b9b10c24",
          "sha1": "f8563a18b02c0aa1f7cd1ee298e76abd3514822b",
          "md5": "79afaa9f079a0f14db4929387dbf0592"
        }
      ]
    }
  ]
}
